In [ ]:
import numpy as np
import pandas as pd
marks = np.array([78,90,98,90,68])
print("Numpy version:",np.__version__)
print("Panda version:",np.__version__)
print("Marks:",marks)
print("Type:",type(marks))
print("Number of dimensions:",marks.ndim)
print("Shape:",marks.shape)
print("Number of elements:",marks.size)
print("Original:",marks)
print("Add 5:",marks+5)
print("Multiply by 2:",marks*2)
print("Divide by 2:",marks/2)
print("Square:",marks**2)
print("Sum:",marks.sum())
print("Mean:",marks.mean())
print("Maximum:",marks.max())
print("Minimum:",marks.min())
print("First mark:",marks[0])
print("Second mark:",marks[1])
print("Last mark:",marks[-1])
print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From index 2:",marks[:2])
print("Every second element:",marks[::2])

Numpy version: 2.1.3
Panda version: 2.1.3
Marks: [78 90 98 90 68]
Type: <class 'numpy.ndarray'>
Number of dimensions: 1
Shape: (5,)
Number of elements: 5
Original: [78 90 98 90 68]
Add 5: [ 83  95 103  95  73]
Multiply by 2: [156 180 196 180 136]
Divide by 2: [39. 45. 49. 45. 34.]
Square: [6084 8100 9604 8100 4624]
Sum: 424
Mean: 84.8
Maximum: 98
Minimum: 68
First mark: 78
Second mark: 90
Last mark: 68
Index 1 to 3: [90 98 90]
First three: [78 90 98]
From index 2: [78 90]
Every second element: [78 98 68]

In [ ]:
import numpy as np
student_marks=np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
])
print(student_marks)
print("Shape:",student_marks.shape)
print("Mean of all values:",student_marks.mean())
print("Column-wise mean:",student_marks.mean(axis=0))
print("Row-wise mean:",student_marks.mean(axis=1))

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)
Mean of all values: 84.44444444444444
Column-wise mean: [78.33333333 89.33333333 85.66666667]
Row-wise mean: [85.         77.         91.33333333]

In [ ]:
import pandas as pd
data = {
    "Name":["Anu","Rahul","Kiran","Priya","A","B","C","D","E","F"],
    "Branch":["CSE","AIML","CSE","AIML","CSE","CSE","AIML","CSE","CSE","AIML"],
    "Marks":[85,91,76,88,90,99,98,90,97,90]
}
df = pd.DataFrame(data)
print("Shape:",df.shape)
print("\nColumns:")
print(df.columns)
df
df.head()
df.tail()
df.describe()
print("First row:")
print(df.iloc[0])
print("\nSecond row:")
print(df.iloc[1])
print("\nFirst three rows:")
print(df.iloc[0:3])
print("\nFirst two rows and first two columns:")
print(df.iloc[0:2,0:2])
print("Rows 1 to 3:Name and Marks:")
print(df.iloc[1:4,0:3])
high_scores = df[df["Marks"]>90]
high_scores
print("Students from CSE:")
display(df[df["Branch"]=="CSE"])

Shape: (10, 3)

Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')
First row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

First two rows and first two columns:
    Name Branch
0    Anu    CSE
1  Rahul   AIML
Rows 1 to 3:Name and Marks:
    Name Branch  Marks
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88
Students from CSE:

    Name Branch  Marks
0    Anu    CSE     85
2  Kiran    CSE     76
4      A    CSE     90
5      B    CSE     99
7      D    CSE     90
8      E    CSE     97

In [ ]:
import pandas as pd
data = {
    "Name":["Asha","Bharat","chetan","Divya","Esha"],
    "Branch":["CSE","AIML","CSE","AIML","CSE"],
    "Marks":[85,91,76,88,90],
    "Attendance":[90,80,98,90,98]
}
students = pd.DataFrame(data)
students
print(students[["Name","Marks"]])


print(students[students["Marks"]>80])
print(students[students["Attendance"]>80])
print(students["Marks"].mean())
print("\nStudents from CSE:")
display(students[students["Branch"]=="CSE"])
display(students[(students["Marks"]>=80)&(students["Attendance"]>85)])

     Name  Marks
0    Asha     85
1  Bharat     91
2  chetan     76
3   Divya     88
4    Esha     90
     Name Branch  Marks  Attendance
0    Asha    CSE     85          90
1  Bharat   AIML     91          80
3   Divya   AIML     88          90
4    Esha    CSE     90          98
     Name Branch  Marks  Attendance
0    Asha    CSE     85          90
2  chetan    CSE     76          98
3   Divya   AIML     88          90
4    Esha    CSE     90          98
86.0

Students from CSE:

     Name Branch  Marks  Attendance
0    Asha    CSE     85          90
2  chetan    CSE     76          98
4    Esha    CSE     90          98

    Name Branch  Marks  Attendance
0   Asha    CSE     85          90
3  Divya   AIML     88          90
4   Esha    CSE     90          98